# Output description {#output-chap .unnumbered}

## In this chapter

<!-- obj add links to relevant parts  -->

<!-- add link in index/user support : sa chap + another chap  -->

<!-- ADD output links to readme pages / R doc  -->

-   what kind of output is produced ?

-   How to identify an output object given an algorithm ? what is uniquely defined

-   What are the output format ?

-   Where is the output available ?

-   How to navigate it ?

-   How to generate it ?

-   List of displayed/generated series (), e.g

-   List of displayed/generated diagnostics, e.g

-   List of displayed/generated parameters, e.g

-   R packages output specificities (str(m))

in R difference between user-defined and default 
default means : directly retrievable from sa_model 

## Scope

SA algorithms vs the rest

here SA related output, set up specific chapter add HF to HF of SA - rjd3...: str(m) - GUI display

generating output from GUI possible only when workspace withh multi-documents

and add non sa related output list of algos - terror - bench and TD -

how does it occur - plug ins R packages

## Use Cases

use case 1

use case 2

and search advices

## SA related algorithms (HF included ?)

## What is displayed or generated ?

### JDemetra+ Output: 3 types of objects

-   series (final and intermediate)

-   parameters

-   diagnostics

### How to identify an output object given an algortithm

what is uniquely defined

-   CODE= concept\*algo

ex preadjut = reg-arima or tramo

Example

-   diagnostic, some are general, some are algo specific ex F test vs m7

-   series

-   paremeter

### Where is output displayed ?

displayed : you have it vs generated you must act

-   gui

-   R packages

#### How to navigate it

### How can output be generated ?

dictionaries

<!-- maj java dicos  -->

generated to files or R objects (lists of lists)

-   gui

Gathered in 2 data structures

-   time series organised in data tables

-   individual data (for each series: parameters and diagnostics)

#### How to generate it

How to identify an output object given an algortithm what is uniquely defined

-   concept\*algo

ex predajsutment = reg-arima or ttramo

Example

-   diagnostic

-   series

-   paremeter

How to identify an output object given an algortithm what is uniquely defined

-   concept\*algo

ex predajsutment = reg-arima or ttramo

Example

-   diagnostic

-   series

-   paremeter

#### Cruncher

here output code, input = cruncher params, table is in cruncher chapter (link )

X13-Arima

-   signal what is out but not relevant

Tramo seats

#### R Dicos /R user defined output

HERE 

rjd3x13, rjd3tramoseats 

link to doc in rjdverse..

##### Filtering useless output 

TS only in X13 and vice versa ?

##### Descripitions in JAVA

##### Table Description  
type
name M7
JD+ output name decomp.M7
..
..






## Differences between V2 and V3

<!-- first: focus on v3 -->

Below different lists We flag differences between v2 and v3

<!-- file from old doc GUI_Output_items.txt in Documents/JD_Quarto_Book_AUX/All_pages -->

<!-- use: https://www.tablesgenerator.com/markdown_tables -->

In the remainder list of nammes Link (auto) with R dictionaries ?

## Series

stored by algo, unique concept

### Table structure !

as pb of width tables broken in 2 parts 

where are auxiliary excel files 
auxiliary R code 
all in "Documents/JD_Quarto_Book_AUX"

#### part 1: GUI + cruncher 

name
description 

#### part 2: R with code

### Final SA series

### Preadjustement / modelling

identical for reg-arima and ts

### X-11 decomposition (start 1)

<!-- (moved from method chapter or left in both ?) -->



part 2

| Code | Description | GUI display (Results Panel) | GUI output - input | cruncher V3 output |
|--------------|--------------|:----------------:|:------------:|:------------:|
| B1 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B2 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B3 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B4 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B5 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B6 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B7 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B8 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B9 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B10 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B11 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B12 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B13 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| B14 | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |

| Code | Description | GUI display (Results Panel) | GUI output - input | cruncher V3 output |
|------|--------------|:--------------:|:------------:|:------------:|
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
| [B1](#m-X11-output) | Linearized Series | Decomposition X-11 \> Table B | decomposition.b1 | decomposition.b1 |
|  |  |  |  |  |

### Seats decomposition (2)

## Diagnostics

obj have all the tests used in BQ and displayed in GUI

stand alone tests: - in GUI - in R (rjd3toolkit)

### Tests on residuals

ONE TEST example : LB TEST, link to M chap what do we describe here

### Seasonality tests

ONE TEST example : Friedman TEST, link to M chap what do we describe here

## Parameters

last

## Cruncher Output (special)

to cruncher chap ?

## R packages (str(model)) output

see how it works 
in part R code will be in tables ?

## Non SA related algorithms

## R packages (str(model)) output

